[package]
name = "aoc-2015"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# for presenters layer
actix-web = "4"
json = "0.12.4"
serde = {version = "1.0.183" , features = ["derive"]}
serde_json = "1.0.105"
const-str ="0.5.6"